version: "3.3"
services:
  postgres:
    image: postgres:10.12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prisma

  postgres-testing:
    image: postgres:10.12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testing
